# List of NSE stocks to screen
# Expanded to include specific sectors: Renewables, Defense, EMS, Tech
# CORRECTIONS APPLIED: Fixed outdated/incorrect symbols
TICKERS = [
    "20 Microns.NS",
    "3B Blackbio.NS",
    "ACC.NS",
    "ADC India.NS",
    "AGI Greenpac.NS",
    "AGI Infra.NS",
    "ASK Automotive.NS",
    "ASM Technologies.NS",
    "Abans Financial.NS",
    "Adcounty Media..NS",
    "Aditya AMC.NS",
    "Aditya Infotech.NS",
    "Aditya Vision.NS",
    "Ador Welding.NS",
    "Advait Energy.NS",
    "Afcom Holdings.NS",
    "Ahluwalia Contr..NS",
    "Ajanta Pharma.NS",
    "Ajmera Realty.NS",
    "Akums Drugs.NS",
    "Algoquant Fin.NS",
    "Alldigi Tech.NS",
    "Alpex Solar.NS",
    "Amber Enterp..NS",
    "Anand Rathi Wea..NS",
    "Antelopus Selan.NS",
    "Anthem Bioscienc.NS",
    "Anupam Rasayan.NS",
    "Apar Inds..NS",
    "Apcotex Industri.NS",
    "Apex Ecotech.NS",
    "Apollo Micro Sys.NS",
    "Arkade.NS",
    "Artemis Medicare.NS",
    "Arvind Ltd.NS",
    "Arvind SmartSp..NS",
    "Ashapura Minech..NS",
    "Ashoka Buildcon.NS",
    "Ather Energy.NS",
    "Australian Prem.NS",
    "Authum Invest.NS",
    "Axis Solution.NS",
    "Axtel Industries.NS",
    "B P C L.NS",
    "BCL Industries.NS",
    "BLS Internat..NS",
    "BMW Industries.NS",
    "BMW Ventures.NS",
    "BSE.NS",
    "Balmer Law. Inv..NS",
    "Balu Forge.NS",
    "Banco Products.NS",
    "Bansal Wire Inds.NS",
    "Basilic Fly Stud.NS",
    "Bayer Crop Sci..NS",
    "Belrise Industri.NS",
    "Benares Hotels.NS",
    "Beta Drugs Ltd.NS",
    "Bhansali Engg..NS",
    "Bharat Seats.NS",
    "Bharti Hexacom.NS",
    "Birlasoft Ltd.NS",
    "Blue Jet Health.NS",
    "Bombay Super Hyb.NS",
    "Bondada Engineer.NS",
    "Borana Weaves.NS",
    "Borosil Renew..NS",
    "C K K Retail.NS",
    "C P C L.NS",
    "C.E. Info System.NS",
    "CFF Fluid.NS",
    "CG Power & Ind.NS",
    "CRISIL.NS",
    "Canara Robeco.NS",
    "Capacit'e Infra..NS",
    "Capillary Tech..NS",
    "Caplin Point Lab.NS",
    "Carysil.NS",
    "Castrol India.NS",
    "Ceinsys Tech.NS",
    "Cello World.NS",
    "Cemindia Project.NS",
    "Centum Electron.NS",
    "Chalet Hotels.NS",
    "Chambal Fert..NS",
    "Choice Intl..NS",
    "Coal India.NS",
    "Coforge.NS",
    "Cohance Life.NS",
    "Concord Control.NS",
    "Corona Remedies.NS",
    "Craftsman Auto.NS",
    "Creative Newtech.NS",
    "Credo Brands.NS",
    "Crizac.NS",
    "Cupid.NS",
    "Cyient DLM.NS",
    "D B Corp.NS",
    "D-Link India.NS",
    "D.P. Abhushan.NS",
    "DDev Plastiks.NS",
    "DEE Development.NS",
    "DOMS Industries.NS",
    "Dam Capital Advi.NS",
    "Data Pattern.NS",
    "Deep Industries.NS",
    "Dhanuka Agritech.NS",
    "Disa India.NS",
    "Divgi Torq.NS",
    "Dolat Algotech.NS",
    "Dr Agarwal's Eye.NS",
    "Dr Lal Pathlabs.NS",
    "Dynacons Sys..NS",
    "Dynamic Cables.NS",
    "E2E Networks.NS",
    "EMS.NS",
    "Easy Trip Plann..NS",
    "Ecos (India).NS",
    "Elantas Beck.NS",
    "Electronics Mart.NS",
    "Ellen.Indl.Gas.NS",
    "Emcure Pharma.NS",
    "Emmvee Photovol..NS",
    "Engineers India.NS",
    "Enviro Infra.NS",
    "Epigral.NS",
    "Esab India.NS",
    "Everest Kanto.NS",
    "Expleo Solutions.NS",
    "FDC.NS",
    "Fedders Holding.NS",
    "Federal-Mogul Go.NS",
    "Fermenta Biotec..NS",
    "Fiem Industries.NS",
    "Firstsour.Solu..NS",
    "Flair Writing.NS",
    "FlySBS Aviation.NS",
    "Force Motors.NS",
    "Fredun Pharma.NS",
    "Frontier Springs.NS",
    "Fujiyama Power.NS",
    "GE Power.NS",
    "GE Shipping Co.NS",
    "GE Vernova T&D.NS",
    "GK Energy.NS",
    "GNA Axles.NS",
    "GPT Infraproject.NS",
    "GRE Renew.NS",
    "GYFTR.NS",
    "Ganesh Benzopl..NS",
    "Ganesh Green.NS",
    "Ganesh Housing.NS",
    "Garden Reach Sh..NS",
    "Garuda Cons.NS",
    "Glaxosmi. Pharma.NS",
    "Glenmark Pharma..NS",
    "Global Education.NS",
    "Godawari Power.NS",
    "Godfrey Phillips.NS",
    "Gokul Agro.NS",
    "Goldiam Intl..NS",
    "Goodluck India.NS",
    "Grauer & Weil.NS",
    "Gravita India.NS",
    "Greenleaf Envi..NS",
    "Grindwell Norton.NS",
    "Guj Pipavav Port.NS",
    "Guj. Themis Bio..NS",
    "Gujarat Energy.NS",
    "Gulf Oil Lubric..NS",
    "Gulshan Polyols.NS",
    "HBL Engineering.NS",
    "Happy Forgings.NS",
    "Health.Global.NS",
    "Hexaware Tech..NS",
    "High Energy Bat..NS",
    "Hindustan Copper.NS",
    "Hindustan Foods.NS",
    "Hindustan Zinc.NS",
    "Hitachi Energy.NS",
    "I O C L.NS",
    "I R C T C.NS",
    "ICRA.NS",
    "IIFL Capital.NS",
    "Icodex Publish..NS",
    "Indiamart Inter..NS",
    "Indian Metals.NS",
    "Indo Amines.NS",
    "Indo SMC.NS",
    "Indo Tech.Trans..NS",
    "Indo Thai Sec..NS",
    "Indo-MIM.NS",
    "Indosolar.NS",
    "Indrapr.Medical.NS",
    "InfoBeans Tech..NS",
    "Ingersoll-Rand.NS",
    "Inox India.NS",
    "Insolation Ener.NS",
    "International Gemological Instit.NS",
    "Inventurus Knowl.NS",
    "Ivalue Infosolut.NS",
    "J Kumar Infra.NS",
    "Jain Resource.NS",
    "Jash Engineering.NS",
    "Jayaswal Neco.NS",
    "Jeena Sikho.NS",
    "Jindal Drilling.NS",
    "Jindal Poly Inve.NS",
    "Jindal Stain..NS",
    "John Cockerill.NS",
    "Jupiter Life Lin.NS",
    "Jyothy Labs.NS",
    "Jyoti CNC Auto..NS",
    "Jyoti Resins.NS",
    "K C P.NS",
    "K.P. Energy.NS",
    "KEC International.NS",
    "KMC Speciality.NS",
    "KP Green Engg..NS",
    "KPIT Technologi..NS",
    "KRBL.NS",
    "KRN Heat Exchan.NS",
    "KSE.NS",
    "Kajaria Ceramics.NS",
    "Kalpataru Proj..NS",
    "Kamdhenu.NS",
    "Kaveri Seed Co..NS",
    "Kellton Tech.NS",
    "Keltech Energies.NS",
    "Kennametal India.NS",
    "Kesar India.NS",
    "Kingfa Science.NS",
    "Kirloskar Oil.NS",
    "Knowledge Marine.NS",
    "Kolte Patil Dev..NS",
    "Kothari Petroche.NS",
    "Kovai Medical.NS",
    "Krishana Phosch..NS",
    "Krishna Defence.NS",
    "Ksolves India.NS",
    "Kwality Pharma.NS",
    "Kwality Wall's.NS",
    "LG Electronics.NS",
    "LMW.NS",
    "Latent View.NS",
    "Life Insurance.NS",
    "Lords Mark Industries.NS",
    "Lumax Auto Tech..NS",
    "Lumax Industries.NS",
    "Lupin.NS",
    "M B Agro Prod..NS",
    "MPS.NS",
    "MSTC.NS",
    "Macpower CNC.NS",
    "Maithan Alloys.NS",
    "Mangalam Cement.NS",
    "Mangalam World..NS",
    "Manoj Vaibhav.NS",
    "Manorama Indust..NS",
    "Marathon Nextgen.NS",
    "Marine Electric..NS",
    "Marksans Pharma.NS",
    "Master Trust.NS",
    "Mayur Uniquoters.NS",
    "Minda Corp.NS",
    "Mobavenue AI Tech.NS",
    "Modern Insulator.NS",
    "Modi Naturals.NS",
    "Modison.NS",
    "Monarch Networth.NS",
    "Monte Carlo Fas..NS",
    "Motisons Jewel.NS",
    "Multi Comm. Exc..NS",
    "NESCO.NS",
    "NGL Fine Chem.NS",
    "NIIT Learning.NS",
    "NMDC.NS",
    "NRB Bearings.NS",
    "NTPC Green Ene..NS",
    "Narayana Hrudaya.NS",
    "Natco Pharma.NS",
    "Natl. Aluminium.NS",
    "Navin Fluo.Intl..NS",
    "Netweb Technol..NS",
    "Network People.NS",
    "Newgen Software.NS",
    "Nippon Life Ind..NS",
    "Nirlon.NS",
    "Nitta Gelatin.NS",
    "Nurture Well Industries.NS",
    "OBSC Perfection.NS",
    "Oil India.NS",
    "Om Power Transmission.NS",
    "OneSource Speci..NS",
    "Onward Technolog.NS",
    "Optivalue Tek.NS",
    "Oriana Power Ltd.NS",
    "Orient Cement.NS",
    "Oswal Pumps.NS",
    "P & G Hygiene.NS",
    "P N Gadgil Jewe..NS",
    "POCL Enterprises.NS",
    "PTC India Fin.NS",
    "PTC Industries.NS",
    "Pace Digitek.NS",
    "Panacea Biotec.NS",
    "Panama Petrochem.NS",
    "Parag Milk Foods.NS",
    "Paramount Comm..NS",
    "Paras Defence.NS",
    "Park Medi World.NS",
    "Parmeshwar Metal.NS",
    "Pasupati Acrylon.NS",
    "Patanjali Foods.NS",
    "Pearl Global Ind.NS",
    "Pennar Industrie.NS",
    "Persistent Systems.NS",
    "Petronet LNG.NS",
    "Pfizer.NS",
    "Piccadily Agro.NS",
    "Pitti Engg..NS",
    "Pix Transmission.NS",
    "Pokarna.NS",
    "Polycab India.NS",
    "Polyplex Corpn.NS",
    "Pondy Oxides.NS",
    "Power Mech Proj..NS",
    "Prec. Wires (I).NS",
    "Premier Energies.NS",
    "Premier Polyfilm.NS",
    "Privi Speci..NS",
    "Prudent Corp..NS",
    "Pudumjee Paper.NS",
    "Pushpa Jewellers.NS",
    "R R Kabel.NS",
    "R Systems Intl..NS",
    "RACL Geartech.NS",
    "RaajMarg Infra.NS",
    "Radhika Jeweltec.NS",
    "Raghav Product..NS",
    "Railtel Corpn..NS",
    "Rainbow Child..NS",
    "Rajesh Power.NS",
    "Rajoo Engineers.NS",
    "Ram Ratna Wires.NS",
    "Ramky Infra.NS",
    "Rane (Madras).NS",
    "Rashi Peripheral.NS",
    "Ravindra Energy.NS",
    "Raymond Realty.NS",
    "Redtape.NS",
    "Refex Industries.NS",
    "Rishabh Instrum..NS",
    "Route Mobile.NS",
    "Rubicon Research.NS",
    "S C I.NS",
    "SBI Funds Mgt..NS",
    "SEAMEC Ltd.NS",
    "SJS Enterprises.NS",
    "SKM Egg Prod..NS",
    "SML Mahindra.NS",
    "SPARC.NS",
    "SRM Contractors.NS",
    "Saatvik Green.NS",
    "Safari Inds..NS",
    "Sahana Systems.NS",
    "Sai Life.NS",
    "Sai Silks.NS",
    "Saksoft.NS",
    "Salasar Techno.NS",
    "Sambhv Steel.NS",
    "Samhi Hotels.NS",
    "Sandhar Tech.NS",
    "Sandur Manganese.NS",
    "Sarda Energy.NS",
    "Sathlokhar Sys..NS",
    "Schaeffler India.NS",
    "Schneider Elect..NS",
    "Sedemac Mechatro.NS",
    "Senco Gold.NS",
    "Senores Pharma..NS",
    "Seshaasai Tech..NS",
    "Shaily Engineer..NS",
    "Shakti Pumps.NS",
    "Shanthi Gears.NS",
    "Shanti Gold.NS",
    "Sharda Cropchem.NS",
    "Sharda Motor.NS",
    "Share India Sec..NS",
    "Shilchar Tech..NS",
    "Shivalik Bimetal.NS",
    "Shraddha Prime.NS",
    "Shringar House.NS",
    "Sigma Advanced System.NS",
    "Sigma Solve.NS",
    "Signpost India.NS",
    "Sika Interplant.NS",
    "Silver Touch.NS",
    "Sirca Paints.NS",
    "Siyaram Silk.NS",
    "Skipper.NS",
    "Sky Gold & Diam..NS",
    "Sobhagya Mercant.NS",
    "Solar Industries.NS",
    "Solarworld Ene..NS",
    "Solex Energy.NS",
    "Spectrum Electr..NS",
    "Steelcast.NS",
    "Stellant Secu..NS",
    "String Metaverse.NS",
    "Stylam Industrie.NS",
    "Styrenix Perfor..NS",
    "Sudeep Pharma.NS",
    "Sumitomo Chemi..NS",
    "Sun TV Network.NS",
    "Sundram Fasten..NS",
    "Sunshield Chem..NS",
    "Swaraj Engines.NS",
    "T B Z.NS",
    "T R I L.NS",
    "TAAL Tech.NS",
    "TCS.NS",
    "TD Power Systems.NS",
    "TVS Motor Co..NS",
    "Tanfac Inds..NS",
    "Tanla Platforms.NS",
    "Tasty Bite Eat..NS",
    "Tata Elxsi.NS",
    "Technocraf.Inds..NS",
    "Tembo Global.NS",
    "Tenneco Clean.NS",
    "Thangamayil Jew..NS",
    "The Bombay Burmah.NS",
    "Thejo Engg..NS",
    "Thyrocare Tech..NS",
    "Timex Group.NS",
    "Tips Music.NS",
    "Titan Biotech.NS",
    "Titan Company.NS",
    "Transport Corp..NS",
    "Transrail Light.NS",
    "Travel Food.NS",
    "Uni Abex Alloy.NS",
    "Univastu India.NS",
    "Uno Minda.NS",
    "V-Marc India.NS",
    "V2 Retail.NS",
    "VST Industries.NS",
    "Vadilal Inds..NS",
    "Vaibhav Global.NS",
    "Varroc Engineer.NS",
    "Varun Beverages.NS",
    "Vedant Fashions.NS",
    "Veedol Corporat.NS",
    "Venus Remedies.NS",
    "Vertis Infra..NS",
    "Vesuvius India.NS",
    "Vijaya Diagnost..NS",
    "Vikram Solar.NS",
    "Vikram Thermo.NS",
    "Vinati Organics.NS",
    "Vintage Coffee.NS",
    "Vision Infra.NS",
    "Viviana Power.NS",
    "Voltas.NS",
    "Waaree Energies.NS",
    "Waaree Renewab..NS",
    "Wakefit Innovati.NS",
    "Websol Energy.NS",
    "Welspun Corp.NS",
    "West Coast Paper.NS",
    "Whirlpool India.NS",
    "Wonder Electric..NS",
    "Yaap Digital.NS",
    "Yasho Industries.NS",
    "Yatharth Hospit..NS",
    "Yatra Online.NS",
    "Zaggle Prepaid.NS",
    "Zen Technologies.NS",
    "Zensar Tech..NS",
    "eClerx Services.NS",
    "eMudhra.NS",
    "Knack Packaging.NS",
    "Siemens Ener.Ind.NS",
    "Ramco Systems.NS",
    "Ashika Global Securities..NS",
    "JSW Cement.NS",
    "CEAT.NS",
    "Wheels India.NS",
    "JK Tyre & Indust.NS",
    "Teerth Gopicon.NS",
    "Ravi Leela Gran.NS",
    "Trident Lifeline.NS",
    "Arigato Universe.NS",
    "Oval Projects.NS",
    "HVAX Technolog..NS",
    "Swastika Castal.NS",
    "V R Infraspace.NS",
    "Vaxtex Cotfab.NS",
    "SBC Exports.NS",
    "Aartech Solonics.NS",
    "Sudarshan Pharma.NS",
    "Pramara Promotio.NS",
    "Monika Alcobev.NS",
    "WPIL.NS",
    "GRM Overseas.NS",
    "C2C Advanced.NS",
    "Kaynes Tech.NS",
    "Solarium Green.NS",
    "Aeroflex Enter..NS",
    "Azad Engineering.NS",
    "Rama Telecom.NS",
    "Crop Life Scienc.NS",
    "Garnet Intl..NS",
    "Rhetan TMT Ltd.NS",
    "Inox Wind.NS",
    "Artefact Project.NS",
    "Punjab Commun..NS",
    "Dhanashree Elect.NS",
    "Hubtown.NS",
    "Ashoka Metcast.NS",
    "Zenith Drugs.NS",
    "Affordable Robo..NS",
    "Polysil Irrigati.NS",
    "Jay Kailash.NS",
    "Jaykay Enter..NS",
    "Vindhya Telelink.NS",
    "Gorani Industrie.NS",
    "RIR Power Electr.NS",
    "Raghunath Intl..NS",
    "Neelam Linens.NS",
    "Pentagon Rubber.NS",
    "Panabyte Tech.NS",
    "RDB Infrastruc..NS",
    "Citichem India.NS",
    "Telogica.NS",
    "Wardwizard Inno..NS",
    "Promax Power.NS",
    "Neogen Chemicals.NS",
    "Indobell Insul..NS",
    "S. V. J. Enterp..NS",
    "Drone Destinatio.NS",
    "Saptarishi Agro.NS",
    "Yug Decor.NS",
    "Ampvolts.NS",
    "Rexpro Enter..NS",
    "Medicamen Biotec.NS",
    "SMVD Poly Pack.NS",
    "AKI India.NS",
    "SVS Ventures.NS",
    "Unichem Labs..NS",
    "Popular Found..NS",
    "New Light Industries.NS",
    "Swan Corp.NS",
    "Oriental Trimex.NS",
    "Akash InfraProj..NS",
    "Saboo Sodium.NS",
    "Magenta Life.NS",
    "Arrowhead Sepera.NS",
    "Confidence Fut..NS",
    "Dalmia Industria.NS",
    "Aik Pipes & Poly.NS",
    "TIL.NS",
    "Indrayani Biotec.NS",
    "Jiwanram Sheo.NS",
    "Navkar Urban..NS",
    "Mercury EV-Tech.NS",
    "Simplex Infra.NS",
    "Jyoti Structures.NS",
    "Kamdhenu Venture.NS",
    "United Interacti.NS",
    "Gautam Gems.NS",
    "Guj Apollo Inds.NS",
    "Shiva Granito.NS",
    "Heads UP Venture.NS",
    "Ravikumar Distll.NS",
    "Minal Industries.NS",
    "Electro Force.NS",
    "BGIL Films & Tec.NS",
    "Urja Global.NS",
    "Groarc Industrie.NS",
    "Kavveri Defence.NS",
    "Droneacharya Aer.NS",
    "Sh. Krish. Infr..NS",
    "Nagpur Power.NS",
    "Rajnish Retail.NS",
    "JTL Defence.NS",
    "ATC Energies.NS",
    "Vantage Knowledg.NS",
    "7NR Retail Ltd.NS",
    "Anik Industries.NS",
    "Jet Solar.NS",
    "Indifra Ltd.NS",
    "Pervasive Comm..NS",
    "AFLOAT Enterpris.NS",
    "Bharat Global.NS",
    "Shukra Jewellery.NS",
    "Shrydus Indust..NS",
    "Mrugesh Trading.NS",
    "Kaiser Corporat..NS",
    "Sunraj Diamond.NS",
    "Diggi Multitrade.NS",
    "Kemp & Co..NS",
    "Landmarc Leisur..NS",
    "Krishna Capital.NS",
    "Atlas Cycles.NS",
    "Tahmar Enterp..NS",
    "Ideaforge Tech.NS",
    "Welcure Drugs.NS",
    "Mish Designs.NS",
    "MPDL Ltd.NS",
    "Andrew Yule & Co.NS",
    "Vishnu Prakash R.NS",
    "TCM.NS",
    "Ind-Agiv Commer..NS",
    "RRP Defense.NS",
    "RKD Agri.NS",
    "Tejas Networks.NS",
    "Quadrant Future.NS",
    "SVP Global.NS",
    "Pan Electronics.NS",
    "Chrome Silicon.NS",
    "Facor Alloys.NS",
    "Franklin Indust..NS",
    "Hemo Organic.NS",
    "Innovassynth Technologies.NS",
    "Flexituff Vent..NS",
    "Kati patang Life.NS",
    "Adhata Global.NS",
    "Vista Pharma..NS",
    "Epuja Spiritech.NS",
    "Regency Ceramics.NS",
    "Switching Tech..NS",
    "HMT.NS"
]

# --- MULTIBAGGER HUNT FRAMEWORK (MARCH 2026) ---
# Derived from structural framework for falling markets.
MULTIBAGGER_HUNT = {
    "desc": "Comprehensive Hunt for structural multibaggers (V4.1)",
    "filters": {
        "sales_growth_5y_min":  0.15,    # Annualized Sales > 15%
        "pat_growth_5y_min":    0.15,    # PAT Growth > 15%
        "roe_min":              0.15,    # ROE > 15%
        "roce_min":             0.15,    # ROCE > 15%
        "peg_max":              1.0,     # PEG < 1
        "debt_equity_max":      0.50,    # Debt/Equity < 0.5
        "pledge_pct_max":       0.0,     # Strictly zero pledge
        "promoter_pct_min":     50.0,    # Promoter skin in the game
        "cfo_to_pat_min":       0.8,     # OCF / Net Profit > 0.8
        "market_cap_max":       5000,    # Small/Mid cap space
        "piotroski_min":        6,       
    }
}

# Targeted hunting grounds for structural multibaggers
SECTORS = [
    # Defense Electronics & Systems
    "BEL.NS", "DATAPATTNS.NS", "PARAS.NS", "ZENTEC.NS", "ASTRAMICRO.NS",
    # Specialty Chemicals (China+1 survivors)
    "CLEAN.NS", "NAVINFLUOR.NS", "VINATIORGA.NS", "DEEPAKNTR.NS", "AETHER.NS",
    # Healthcare & Diagnostics (Immune consumption)
    "METROPOLIS.NS", "VIJAYA.NS", "NH.NS", "KIMS.NS",
    # EMS / Electronics Mfg (PLI tailwinds)
    "DIXON.NS", "KAYNES.NS", "AMBER.NS", "SYRMA.NS",
    # Agrochemicals (Rural recovery)
    "PIIND.NS", "SUMICHEM.NS",
    # Capital Goods / Capex Cycle
    "GRINDWELL.NS", "AIAENG.NS", "CARBORUNIV.NS",
    # Building Materials (Real Estate proxy)
    "ASTRAL.NS", "SUPREMEIND.NS", "POLYCAB.NS",
    # Platform Businesses (Market infrastructure)
    "CDSL.NS", "CAMS.NS", "BSE.NS",
    # Branded Consumption / FMCG Midcap
    "RADICO.NS", "BIKAJI.NS", "DODLA.NS", "JYOTHYLAB.NS"
]
